# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        unsupevised: 1
        contrastive learning: 1
        self-supervised: 1
        Self-Supervised: 1
        

# 通知の閾値
score_threshold: 0
